App/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*- 
# @author: xiaofu
# @date: 2020-Aug-16
from django.urls import path, include

from App import views
from Shop import settings

urlpatterns = [
    path('home/', views.home, name='home'),
    path('market/', views.market, name='market'),
    path('cart/', views.cart, name='cart'),
    path('mine/', views.mine, name='mine'),
    path('test/', views.test, name='test'),
    path('testlist/', views.testlist, name='testlist'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('checkuser/', views.checkuser, name='checkuser'),
    path('checkemail/', views.checkemail, name='checkemail'),
    path('logout/', views.logout, name='logout'),
    path('activate/', views.activate, name='activate'),
    path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('delete_from_cart/', views.delete_from_cart, name='delete_from_cart'),
    path('change_select_state/', views.change_select_state, name='change_select_state'),
    path('delete_in_cart/', views.delete_in_cart, name='delete_in_cart'),
    path('add_in_cart/', views.add_in_cart, name='add_in_cart'),
    path('cart_all_unselect/', views.cart_all_unselect, name='cart_all_unselect'),
    path('cart_all_select/', views.cart_all_select, name='cart_all_select'),
    path('make_order/', views.make_order, name='make_order'),
    path('orderdetails/', views.orderdetails, name='orderdetails'),
    path('orderlist_not_pay/', views.orderlist_not_pay, name='orderlist_not_pay'),
    path('paid/', views.paid, name='paid'),  # 一个假的支付接口
    path('alipay/', views.alipay, name='alipay'),  # 支付宝沙盒的测试接口
]

Shop/urls.py
from django.contrib import admin
from django.urls import path, include

from Shop import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include(('App.urls', 'shop'))),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

App/models.py
from django.db import models


# Create your models here.

# class Test(models.Model):
#     name = models.CharField(max_length=16)
#     location = models.CharField(max_length=255)
from App.constants import ORDER_NOT_PAID


class Main(models.Model):
    img = models.CharField(max_length=255)  # 图片地址
    name = models.CharField(max_length=64)  # 图片名称
    trackid = models.IntegerField(default=1)  # 图片id

    class Meta:
        abstract = True


class MainSwiper(Main):
    class Meta:
        db_table = 'MainSwiper'


class MainNav(Main):
    class Meta:
        db_table = 'MainNav'


class MainMustBuy(Main):
    class Meta:
        db_table = 'MainMustBuy'


class GoodType(models.Model):
    typeid = models.IntegerField(default=1)
    typename = models.CharField(max_length=32)
    childtypenames = models.CharField(max_length=255)
    typesort = models.IntegerField(default=1)

    class Meta:
        db_table = 'GoodType'


class Goods(models.Model):
    """
    productid,productimg,productname,productlongname,isxf,pmdesc,
    specifics,price,marketprice,categoryid,childcid,childcidname,dealerid,storenums,productnum
    """
    productid = models.BigIntegerField(default=1)
    productimg = models.CharField(max_length=255)
    productname = models.CharField(max_length=128)
    productlongname = models.CharField(max_length=255)
    isxf = models.BooleanField(default=0)
    pmdesc = models.CharField(max_length=64)
    specifics = models.IntegerField(default=0)
    price = models.FloatField(default=0)
    marketprice = models.FloatField(default=0)
    categoryid = models.IntegerField(default=1)
    childcid = models.IntegerField(default=1)
    childcidname = models.CharField(max_length=128)
    dealerid = models.IntegerField(default=1)
    storenums = models.IntegerField(default=1)
    productnum = models.IntegerField(default=1)

    class Meta:
        db_table = 'Goods'


class User(models.Model):
    username = models.CharField(max_length=32, unique=True)
    email = models.CharField(max_length=64, unique=True)
    password = models.CharField(max_length=256)
    icon = models.ImageField(upload_to='icons/%Y/%m/%d/')
    is_active = models.BooleanField(default=False)
    is_delete = models.BooleanField(default=False)

    class Meta:
        db_table = 'User'


class Cart(models.Model):
    c_user = models.ForeignKey(User, on_delete=models.CASCADE)
    c_good = models.ForeignKey(Goods, on_delete=models.CASCADE)
    c_goods_num = models.IntegerField(default=1)
    c_is_selected = models.BooleanField(default=True)  # 加到车里面默认选中
    class Meta:
        db_table = 'Cart'


class Order(models.Model):
    o_user = models.ForeignKey(User,on_delete=models.CASCADE)
    o_price = models.FloatField(default=0)
    o_time = models.DateTimeField(auto_now=True)
    o_status = models.IntegerField(default=ORDER_NOT_PAID)
    class Meta:
        db_table = 'Order'

class OrderGoods(models.Model):
    o_order = models.ForeignKey(Order,on_delete=models.CASCADE)
    o_goods = models.ForeignKey(Goods,on_delete=models.CASCADE)  # 也可以用复制的方式保留历史信息，这里直接用外键
    o_goods_num = models.IntegerField(default=1)
    class Meta:
        db_table = 'OrderGoods'

templates/order/order_detail.html
{% extends 'base_order.html' %}
{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'ecomm/order/css/order_detail.css' %}">
{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'ecomm/order/js/order_detail.js' %}"></script>
{% endblock %}

{% block content %}
    <div id="order_detail" class="container">
        <h6>订单编号：{{ order.id }}</h6>
        <ul>
            {% for ordergoods in order.ordergoods_set.all %}
                <li class="menuList">
                    <a href="#">
                        <img src="{{ ordergoods.o_goods.productimg }}" alt="{{ ordergoods.o_goods.productlongname }}">
                        <p>{{ ordergoods.o_goods.productlongname }}</p>
                        <p class="presentPrice">{{ ordergoods.o_goods.price }}</p>
                    </a>

                    <section>
                        <span>{{ ordergoods.o_goods_num }}</span>
                    </section>
                </li>
            {% endfor %}
        </ul>

        <h6 class="totalprice">总价：<span class="total_price">{{ order.o_price }}</span></h6>
        <button orderid="{{ order.id }}" id="alipay" class="btn btn-success btn-block">支付</button>
    </div>
{% endblock %}

templates/order/orderlist_not_pay.html
{% extends 'base_order.html' %}
{% load static %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'ecomm/order/js/orderlist_not_pay.js' %}"></script>
{% endblock %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'ecomm/order/css/order_detail.css' %}">
{% endblock %}

{% block content %}
    <div id="orderlist_not_pay" class="container">
        <ol>
            {% for order in orders %}
                <li>
                    <ul class="order" orderid="{{ order.id }}">
                        <h6>订单编号：{{ order.id }}</h6>
                        {% for ordergoods in order.ordergoods_set.all %}
                            <li class="menuList">
                                <a href="#">
                                    <img src="{{ ordergoods.o_goods.productimg }}"
                                         alt="{{ ordergoods.o_goods.productlongname }}">
                                    <p>{{ ordergoods.o_goods.productlongname }}</p>
                                    <p class="presentPrice">{{ ordergoods.o_goods.price }}</p>
                                </a>

                                <section>
                                    <span>{{ ordergoods.o_goods_nums }}</span>
                                </section>
                            </li>
                        {% endfor %}
                    </ul>
                </li>
            {% endfor %}

        </ol>
    </div>
{% endblock %}